# Generated by Django 5.1.3 on 2024-12-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTema', models.CharField(blank=True, max_length=32, null=True)),
                ('descripcionTema', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(blank=True, max_length=64, null=True)),
                ('numeroUsuario', models.CharField(blank=True, max_length=32, null=True)),
                ('direccionUsuario', models.CharField(blank=True, max_length=64, null=True)),
                ('areaUsuario', models.CharField(blank=True, max_length=32, null=True)),
                ('descripcionUsuario', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
