# Generated by Django 5.1.3 on 2024-12-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0003_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='contenidoArticulo',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tituloArticulo',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tema',
            name='descripcionTema',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='nombreTema',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
